nanxiaobei/hugo-paper

layouts/partials/header.html

It doesn't seem standard or useful and just adds to the bytes of each page.

Remove meta renderer tag from header

---

layouts/partials/header.html

This PR allows us to customize paper theme. In my use-case, I'd like to use a custom stylesheet.
The file name of `header-include.html` is from https://gohugo.io/templates/partials/#example-header-html.

Make theme customizable

---

layouts/_default/list.html
layouts/_default/single.html

Previously it wasn't possible to change the date format and I think this an important thing to have in the theme because every country has different formats. After that PR, it will be possible to change the date format in the `config.toml` file like this:
```toml
[params]
dateFormat = "January 2, 2006"
```

Add a way to change the date format with 'dateFormat' site param

---

layouts/partials/header.html

When building the site with Hugo 0.55.5, I get the following warning: 
> Page's .Hugo is deprecated and will be removed in a future release. Use the global hugo function.
Replacing .Hugo with hugo in header.html removes the warning.

Use global hugo function

---

static/css/style.css

This is a problem in Firefox because Firefox displays markers(bullet points) of `<li>` element just before the inline contents of the elements. But Chrome displays them before the element, not depending on the content of the `<li>` element. So it wasn't visible on Chrome but it's in Firefox. This CSS change will remove that in Firefox too.
Before:
After:

Remove the marker of menu <ul> element to fix the style in Firefox

---

layouts/partials/header.html
static/custom.css

The existing theme makes customization difficult, because in order to add or override styles you need to copy and paste the entire header partial so you can link your own stylesheets, or copy and paste the entire `style.css` file. This change adds an initially empty `custom.css` file that can be easily overridden to add custom styles or override existing ones.
As a use case, I've had to do this for my site to add syntax highlighting for code blocks following the official Hugo documentation.

Add support for custom styles and overrides.

---

layouts/partials/header.html

Generated RSS file name can be changed in config:
```yaml
outputFormats:
RSS:
mediatype: 'application/rss'
baseName: 'rss'
```
But template comtains "hardcoded" `index.xml` value. This changes improve this behavior

Fix RSS links

---

layouts/partials/header.html

Light is ignored, since it can mean 'unset'.
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Add support for prefers-color-scheme: dark.

---

i18n/id.yaml

_**Note**: It should be translate to **"Halaman Sebelumnya"** and **"Halaman Selanjutnya"**. However, it is too long and will not be good when opened on a small screen because there is no space between the buttons._

Add i18n support for Indonesian

---

layouts/partials/header.html

This code `{{ if .Title }}{{ .Title }} - {{ end }}` also reads the site title so there is double titles on the homepage.
I just trying to fix it. Please, check my pull request and let me know if something goes wrong with my configuration.

Fixed double titles on homepage

---

layouts/partials/head.html

I've recently moved to this theme and love this beautiful theme.
I noticed that my Google Analytics tags(v4) are not be applied. This pull request is to fix that.
FYI:
[https://gohugo.io/templates/internal/#use-the-google-analytics-template](https://gohugo.io/templates/internal/#use-the-google-analytics-template)
> When using Google Analytics v4 use _internal/google_analytics.html.

add-google-analytics-v4-support

---

layouts/_default/single.html

Static pages within a blog might not have a publish date. For example an "about" page. With this tweak, one can just omit the date field in the page's metadata and the output won't show the default date.

Date is hidden when none is provided

---

layouts/partials/head.html

In the head of the page, the icons for the dark mode are incorrectly preloaded, the request is `https://hugo-paper.vercel.app/theme.{{ if site.Params.monoDarkIcon }}svg{{ else }}png{{ end }}` instead of `https://hugo-paper.vercel.app/theme.png` or `https://hugo-paper.vercel.app/theme.svg`.
Open the console on the [demo](https://hugo-paper.vercel.app/) to see the 404 request.

Fix preload dark icon

---

layouts/partials/header.html

Adding rel="me" to social links for domain identification [https://microformats.org/wiki/rel-me](https://microformats.org/wiki/rel-me)
Mostly for [Mastodon](https://joinmastodon.org/) domain verification purposes.

Add rel="me" param to social links

---

layouts/partials/header.html

This PR removes spaces in header to allow rel="me" to work properly.

Remove spaces in heder url

---

layouts/partials/header.html

when the config file doesn't provide baseURL, there would be a bug that title's link is not home page's link.

fix title's link when there is no baseURL in config file

---

README.md

Hugo has now changed the default configuration file name to "hugo" and they are also suggesting users to rename them. This change will hopefully help new users who are just getting started.
https://gohugo.io/getting-started/configuration/

Update README.md to use new configuration file name

---

layouts/partials/head.html

Hey! Thank you for this theme!
I was looking into the code and I realized that the `:=` operator will create a new variable instead of overriding the previous one.
So here is the fix :tada:

Fix theme.svg preload

---

README.md

Hugo docs means user need initialize go mod system before using modules,  
so I think `hugo mod init` comamnd with *this* repo will mislead theme users.

fix[README.md]: Correct hugo command of use as module secion.

---

README.md
layouts/partials/math.html

I noticed the theme was using a CDN for the KaTeX library. In context of security it may be preferable to have those libraries locally, from the same domain. I'm open to change this pull-request to work in another way (different variable name, another way of achieving the same result, etc.) if needed.
The patch adds a local_katex variable, which if set, will load the JS/CSS from the base URL. The user of the theme needs to place these files in the page source `static/` folder (so it's up to the owner of the site to control the version/files).

Add configurable KaTeX location

---

layouts/partials/footer.html

`hugo.toml` supports a "copyright" option, but theme doesn't.
This PR adds support for custom copyright in the footer. If copyright is not specified, the default version (which is hardcoded now) is used ("© (current year) (site title)")

Customization of copyright in footer

---

layouts/partials/footer.html
layouts/partials/head.html

Hi @nanxiaobei - thank you so much for this beautiful Hugo theme!
I noticed one issue with it when using it, which is that the titles collapse spaces between the page title and the site title, and the same in the footer in the copyright message.
You can see in this screenshot how the title looks on your demo site compared with mine:
And the fixed version of the footer on mine:
The fix is to remove the collapsing `-` from a couple of the partials. I wondered if you might consider this PR to bring these changes upstream.
Thanks so much!

Uncollapse templates that want spaces
